sudo: false
dist: trusty
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
cache: bundler
script:
  - bundle exec rspec --format documentation
env:
  - AWS_CREDENTIAL_RETRIES=0 AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_REGION=us-east-1
notifications:
  email: false
git:
  submodules: false
