sudo: false
dist: trusty
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
cache: bundler
script:
  - bundle exec rspec --format documentation
env:
  - AWS_RETRIES=0
notifications:
  email: false
git:
  submodules: false
